### Numpy 배열의 연산

#### 리스트 연산과 Numpy 배열의 연산 비교:

In [4]:
import numpy as np

In [5]:
a = [1, 2, 3]

In [6]:
a + a

[1, 2, 3, 1, 2, 3]

In [7]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
b = np.array([1, 2, 3])

In [9]:
b*3

array([3, 6, 9])

In [10]:
b + b

array([2, 4, 6])

In [11]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Numpy 배열의 연산:

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
a+b

array([5, 7, 9])

In [15]:
a-b

array([-3, -3, -3])

In [16]:
a*b

array([ 4, 10, 18])

In [17]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

In [3]:
# broadcasting은 넘어감.(array의 size가 mismatch 될 때 자동으로 resize 하여 진행된다.

array([2, 3, 4, 5, 6, 7])

#### 연산의 벡터화 (universal function): 넘파이 배열을 넣고 연산했을 때 넘파이 배열을 반환해주는 함수, 벡터 하나하나마다 대입해서 요소에 적용해주는 것. 집계 함수는 universal이 아니다.

In [19]:
x = np.array([0, 1, 2, 3, 4, 5]) # np.arange(6)

In [20]:
pow(10, x)

array([     1,     10,    100,   1000,  10000, 100000], dtype=int32)

In [21]:
x**3

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [22]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [23]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [24]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

#### Numpy가 제공하는 함수:

In [ ]:
np.random.seed(123) # 완벽한 랜덤은 컴퓨터가 만들 수 없다. random처럼 보이는 sequence만 만들수 있다.
# 초기 위치를 잡는 역할. 아무 숫자나 상관 없다.
a = np.random.randint(1, 11, size=1000)

In [ ]:
np.unique(a)

In [ ]:
np.median(a)

In [ ]:
np.sum(a)

In [ ]:
np.round(np.var(a),2) # 반올림, 소수점 몇자리 까지 keeping하나

In [ ]:
np.round(np.mean(a),2)

In [ ]:
np.round(np.std(a),2)

In [ ]:
np.max(a) 

In [ ]:
np.min(a)

#### 배열의 메서드로 제공되는 함수: np쓸 필요 없이 바로 쓸 수 있는 메소드

In [ ]:
x=np.arange(1,11)

In [ ]:
x.sum()

In [ ]:
x.mean()

In [ ]:
x.std()

In [ ]:
x.var()

In [ ]:
x.cumsum()

In [ ]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

In [ ]:
print(y.mean(axis=0)) # 세로 column

In [ ]:
print(y.mean(axis=1)) # 가로 row

In [ ]:
z = np.random.randint(10,size=1000)

In [ ]:
z.max()

In [ ]:
z.min()

In [ ]:
(z > 5).sum()

In [ ]:
np.unique(z)

In [ ]:
sorted(set(z))

In [ ]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [ ]:
a.argmax() # max의 위치

In [ ]:
a.argmin() # min의 위치